version: '2.4'

#docker network create -d macvlan \
#  --subnet=172.16.86.0/24 \
#  --gateway=172.16.86.1 \
#  -o parent=eth0 pub_net


services:

    homeassistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi4-homeassistant:stable
        volumes:
            - ./data/homeassistant-config:/config
            - /etc/localtime:/etc/localtime:ro
            # - /var/run/restartd_signal:/var/run/restartd_signal
        restart: always
        network_mode: host
        environment:
            TZ: America/Montevideo
        logging:
            options:
                max-size: 10m
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ha-internal.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
            - "traefik.http.routers.ha-internal.entrypoints=web"
            - "traefik.http.routers.ha-insecure.rule=Host(`${EXTERNAL_DOMAIN}`)"
            - "traefik.http.routers.ha-insecure.entrypoints=web"
            - "traefik.http.routers.ha-insecure.middlewares=redirecthttps@file,riptp@file"
            - "traefik.http.routers.ha.rule=Host(`${EXTERNAL_DOMAIN}`)"
            - "traefik.http.routers.ha.entrypoints=websecure"
            - "traefik.http.routers.ha.middlewares=riptp@file"
            - "traefik.http.routers.ha.tls=true"
            - "traefik.http.routers.ha.tls.certresolver=le"
            - "traefik.http.services.ha.loadbalancer.server.port=8123"








    # homeassistant:
    #     container_name: home-assistant
    #     image: homeassistant/raspberrypi4-homeassistant:stable
    #     volumes:
    #         - ./data/homeassistant-config:/config
    #         #- /etc/localtime:/etc/localtime:ro
    #         # - /var/run/restartd_signal:/var/run/restartd_signal
    #     restart: always
    #     # network_mode: host
    #     networks:
    #         - pub_net
    #         - traefik_proxy
    #     environment:
    #         TZ: America/Montevideo
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-size: "5m"
    #             max-file: "10"
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
    #         - "traefik.http.routers.homeassistant.entrypoints=web"
    #         - "traefik.http.routers.homeassistant.service=pihole"
    #         - "traefik.http.services.homeassistant.loadbalancer.server.port=8081"
    #         # config crada por mi 1
    #         # - "traefik.enable=true"
    #         # - "traefik.http.routers.ha-internal.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
    #         # - "traefik.http.routers.ha-internal.entrypoints=web"
    #         # - "traefik.http.services.ha.loadbalancer.server.port=8123"
    #         #configuracion creda por mi 2
    #         # - "traefik.enable=true"
    #         # - "traefik.http.routers.ha.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
    #         # - "traefik.http.routers.ha.entrypoints=web"
    #         # - "traefik.http.routers.ha.service=portainer"
    #         # - "traefik.http.services.ha.loadbalancer.server.port=8123"
    #         #configuracion que tenia
    #         # - "traefik.enable=true"
    #         # - "traefik.http.routers.ha-internal.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
    #         # - "traefik.http.routers.ha-internal.entrypoints=web"
    #         # - "traefik.http.routers.ha-insecure.rule=Host(`${EXTERNAL_DOMAIN}`)"
    #         # - "traefik.http.routers.ha-insecure.entrypoints=web"
    #         # - "traefik.http.routers.ha-insecure.middlewares=redirecthttps@file,riptp@file"
    #         # - "traefik.http.routers.ha.rule=Host(`${EXTERNAL_DOMAIN}`)"
    #         # - "traefik.http.routers.ha.entrypoints=websecure"
    #         # - "traefik.http.routers.ha.middlewares=riptp@file"
    #         # - "traefik.http.routers.ha.tls=true"
    #         # - "traefik.http.routers.ha.tls.certresolver=le"
    #         # - "traefik.http.services.ha.loadbalancer.server.port=8123"
                
    # deconz:
    #     container_name: deconz
    #     image: marthoc/deconz
    #     volumes:
    #         - deconz-config:/root/.local/share/dresden-elektronik/deCONZ
    #         - /etc/localtime:/etc/localtime:ro
    #     restart: always
    #     networks:
    #         - net
    #         - traefik_proxy
    #     environment:
    #         DECONZ_DEVICE: /dev/ttyACM0
    #         DECONZ_WS_PORT: 8443
    #         DECONZ_VNC_MODE: 1
    #     devices:
    #         - /dev/ttyACM0
    #     logging:
    #         options:
    #             max-size: 10m
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.docker.network=traefik_proxy"
    #         - "traefik.http.routers.phoscon.rule=Host(`phoscon.${INTERNAL_DOMAIN}`)"
    #         - "traefik.http.routers.phoscon.entrypoints=web"
    #         - "traefik.http.routers.phoscon.service=phoscon"
    #         - "traefik.http.services.phoscon.loadbalancer.server.port=80"
    #         - "traefik.http.routers.phoscon-ws.rule=Host(`phoscon.${INTERNAL_DOMAIN}`)"
    #         - "traefik.http.routers.phoscon-ws.entrypoints=phosconws"
    #         - "traefik.http.routers.phoscon-ws.service=phoscon-ws"
    #         - "traefik.http.services.phoscon-ws.loadbalancer.server.port=8443"
            
    # mosquitto:
    #     container_name: mosquitto
    #     image: eclipse-mosquitto
    #     volumes:
    #         - ${PERSIST_DATA_PATH}/data/mosquitto-data:/mosquitto/data
    #         - ${PERSIST_DATA_PATH}/data/mosquitto-config:/mosquitto/config
    #     restart: always
    #     networks:
    #         - net
    #         - traefik_proxy
    #     logging:
    #         options:
    #             max-size: 10m
    #     labels:
    #         - traefik.enable=true
    #         - traefik.docker.network=traefik_proxy
    #         - traefik.tcp.routers.mosquitto.entrypoints=mqtt
    #         - traefik.tcp.routers.mosquitto.rule=HostSNI(`*`)
    #         - traefik.tcp.routers.mosquitto.service=mosquitto
    #         - traefik.tcp.services.mosquitto.loadbalancer.server.port=1883

#   influxdb:
#     container_name: influxdb
#     image: influxdb:latest
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "5m"
#         max-file: "10"
#     environment:
#       INFLUXDB_DB: home_assistant
#     volumes:
#       # Data persistency
#       - ./influxdb:/var/lib/influxdb
#     restart: always
#     networks:
#         - net
#         - traefik_proxy


    # mysql:
    #     container_name: database
    #     image: mariadb:latest
    #     volumes: 
    #         - ./data/mariadb-data:/var/lib/mysql
    #     restart: always
    #     networks:
    #         - net
    #         - traefik_proxy
    #     logging:
    #         options:
    #             max-size: 10m
    #     labels:
    #         - traefik.enable=true
    #         - traefik.docker.network=traefik_proxy
    #         - traefik.tcp.routers.mariadb.entrypoints=mysql
    #         - traefik.tcp.routers.mariadb.rule=HostSNI(`*`)
    #         - traefik.tcp.routers.mariadb.service=mariadb
    #         - traefik.tcp.services.mariadb.loadbalancer.server.port=3306


networks:
    pub_net:
        external: true
    # net:
    #     name: homeassistant
    traefik_proxy:
        external: true

