version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    #   - "80:80/tcp"
    #   - "443:443/tcp"
    networks:
      - traefik_proxy
    environment:
      TZ: 'America/Montevideo'
      VIRTUAL_HOST: "pihole.${INTERNAL_DOMAIN}"
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - ./data/pihole-config:/etc/pihole
      - ./data/dnsmasq-config:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"


networks:
  traefik_proxy:
    external: true

