version: '2.4'

services:

    komga:
        image: gotson/komga
        container_name: komga
        ports:
        - 25600:25600
        user: "1000:1000"
        environment:
            - VIRTUAL_HOST=komga.mired        # Dominio del servicio
            - VIRTUAL_PORT=25600                # Puerto interno expuesto por el contenedor
            - CERT_NAME=nginx-selfsigned       # Certificado para Traefik
            - PUID=1000                        # ID de usuario (asegúrate de que coincida con tu sistema)
            - PGID=1000                        # ID de grupo
            - TZ=America/Montevideo 
            # - JAVA_TOOL_OPTIONS=-Xmx2g  # Asignar hasta 2 GB de RAM
        restart: unless-stopped
        volumes:
            - ./data/komga:/config       # Configuración de Calibre-Web
            - /media/DataTemp/media:/media/DataTemp/media    # Biblioteca de libros
        networks:
            traefik_proxy:
                ipv4_address: 172.24.0.16        # Dirección IP dentro de la red Docker
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 279


    # kavita:
    #     image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
    #     container_name: kavita
    #     volumes:
    #         - /media/DataTemp/media:/media/DataTemp/media
    #         - ./data/kavita:/kavita/config     
    #     environment:
    #         - VIRTUAL_HOST=kavita.mired
    #         - VIRTUAL_PORT=5000
    #         - CERT_NAME=nginx-selfsigned
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=America/Montevideo
    #         - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    #     # ports:
    #     #     - "5000:5000"
    #     restart: unless-stopped
    #     networks:
    #       traefik_proxy:
    #         ipv4_address: 172.24.0.11
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-size: "5m"
    #             max-file: "10"


    readarr:
        image: lscr.io/linuxserver/readarr:develop
        container_name: readarr
        environment:
            - VIRTUAL_HOST=readarr.mired
            - VIRTUAL_PORT=8787
            - CERT_NAME=nginx-selfsigned
            - PUID=1000                # ID de usuario en tu sistema
            - PGID=1000                # ID de grupo en tu sistema
            - TZ=America/Montevideo
        volumes:
            - ./data/readarr:/config    # Configuración de Readarr
            - /media/DataTemp/media:/media/DataTemp/media
        # ports:
        #     - 8787:8787                  # Puerto de interfaz web de Readarr
        restart: unless-stopped
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.12
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 100






    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - VIRTUAL_HOST=qbittorrent.mired
            - VIRTUAL_PORT=8080
            - CERT_NAME=nginx-selfsigned
            - PUID=1000                # ID de usuario en tu sistema
            - PGID=1000                # ID de grupo en tu sistema
            - TZ=America/Montevideo
            - WEBUI_PORT=8080
        volumes:
        - ./data/qbittorrent:/config
        - /media/DataTemp/media:/media/DataTemp/media # Carpeta compartida para descargas
        ports:
        # - 8080:8080                  # Puerto para interfaz web de qBittorrent
        - 6881:6881                  # Puerto para conexiones entrantes
        - 6881:6881/udp              # Puerto UDP para conexiones entrantes
        restart: unless-stopped
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.13
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 100




    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - VIRTUAL_HOST=prowlarr.mired
            - VIRTUAL_PORT=9696
            - CERT_NAME=nginx-selfsigned
            - TZ=America/Montevideo
        volumes:
            - /media/DataTemp/media:/media/DataTemp/media
            - ./data/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.14
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 100





    audiobookshelf:
        image: ghcr.io/advplyr/audiobookshelf:latest
        environment:
            - VIRTUAL_HOST=audiobookshelf.mired
            - VIRTUAL_PORT=80
            - CERT_NAME=nginx-selfsigned
            - TZ=America/Montevideo
        # ports:
        # - 13378:80
        restart: unless-stopped
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.20
        volumes:
            - ./data/audiobookshelf/metadata:/metadata
            - ./data/audiobookshelf/config:/config
            - /media/DataTemp/media:/media/DataTemp/media # Carpeta compartida para descargas
        # No memory limit support
        cpu_shares: 279



networks:
    traefik_proxy:
        external: true



