version: '2.4'

#docker network create -d macvlan \
#  --subnet=172.16.86.0/24 \
#  --gateway=172.16.86.1 \
#  -o parent=eth0 pub_net


services:

    homeassistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi4-homeassistant:stable
        volumes:
            - ./data/homeassistant-config:/config
            - /etc/localtime:/etc/localtime:ro
            # - /var/run/restartd_signal:/var/run/restartd_signal
        restart: always
        network_mode: host
        expose:
            - 8123
        environment:
            - TZ=America/Montevideo
        logging:
            options:
                max-size: 10m
        
     #nginx no anda con el network_mode: host entonces esto hace el reenvio
    hass-socat:
        image: rycus86/docker-socat
        container_name: hass-socat
        command: "TCP-LISTEN:8122,fork,reuseaddr TCP:172.24.0.1:8123"
        depends_on: 
            - homeassistant
        environment:       
            - VIRTUAL_HOST=homeassistant.mired
            - VIRTUAL_PORT=8122
            - CERT_NAME=nginx-selfsigned
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.5
        expose:
            - 8122
        restart: unless-stopped







                
    deconz:
        container_name: deconz
        image: marthoc/deconz
        volumes:
            - ./data/deconz-config:/root/.local/share/dresden-elektronik/deCONZ
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.2
        environment:
            - VIRTUAL_HOST=phoscon.mired
            - VIRTUAL_PORT=8480
            - CERT_NAME=nginx-selfsigned
            - DECONZ_WEB_PORT=8480
            - DECONZ_DEVICE=/dev/ttyACM0
            - DECONZ_WS_PORT=8443
            - DECONZ_VNC_MODE=1
        ports:
            - 8443:8443
            - 8480:8480
        devices:
            - /dev/ttyACM0
        logging:
            options:
                max-size: 10m
            
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - ./data/mosquitto-data:/mosquitto/data
            - ./data/mosquitto-config:/mosquitto/config
        restart: always
        networks:
        #     net:
        #         ipv4_address: 172.18.0.2
            traefik_proxy:
                ipv4_address: 172.24.0.7
        environment:
            - VIRTUAL_HOST=mqtt
            - VIRTUAL_PORT=1883
        logging:
            options:
                max-size: 10m

























networks:
    pub_net:
        external: true
    # net:
    #     name: homeassistant
    traefik_proxy:
        external: true



