version: '2.4'

services:
    reverse-proxy:
        container_name: reverse-proxy
        image: jwilder/nginx-proxy
        restart: always
        networks:
          traefik_proxy:
            ipv4_address: 172.24.0.3
        ports:
            - 80:80
            - 443:443
            # - 1883:1883 # mosquito
            # - 3306:3306 # mysql
            # - 8443:8443 # phoscon deconz
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./data/reverse-proxy/vhost.d:/etc/nginx/vhost.d:ro"
            - ./data/reverse-proxy/certs/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
            - ./data/reverse-proxy/certs/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        deploy:
            resources:
                limits:
                    memory: '128m'
        cpu_shares: 279

    homer:
        image: b4bz/homer
        container_name: homer
        volumes:
        - ./data/homer:/www/assets # Make sure your local config directory exists
        user: 1000:1000 # default
        restart: unless-stopped
        networks:
            traefik_proxy:
                ipv4_address: 172.24.0.18
        environment:
            - VIRTUAL_HOST=homer.mired
            - VIRTUAL_PORT=8080
            - CERT_NAME=nginx-selfsigned
            - TZ=America/Montevideo
            - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        deploy:
            resources:
                limits:
                    memory: '64m'
        cpu_shares: 279
    
    # portainer:
    #     container_name: portainer
    #     image: portainer/portainer:1.24.0
    #     restart: always
    #     networks:
    #       traefik_proxy:
    #         ipv4_address: 172.24.0.6            
    #     environment:
    #         - VIRTUAL_HOST=portainer.mired
    #         - VIRTUAL_PORT=9000
    #         - CERT_NAME=nginx-selfsigned 
    #     ports:
    #         - 8000:8000
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - ./data/portainer:/data
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-size: "5m"
    #             max-file: "10"

    # dyndns:
    #     container_name: dyndns
    #     image: oznu/cloudflare-ddns:latest
    #     restart: always
    #     networks:
    #         - host_applications
    #     environment:
    #         API_KEY: "${CLOUDFLARE_API_KEY}"
    #         ZONE: "${DYNDNS_ZONE}"
    #         SUBDOMAIN: "${DYNDNS_SUBDOMAIN}"


networks:
    # host_applications:
    #     name: applications
    #     driver: bridge
    #     ipam:
    #         config:
    #             - subnet: 172.18.0.0/24
    #               gateway: 172.18.0.1
    traefik_proxy:
        name: traefik_proxy
        driver: bridge
        ipam:
            config:
                - subnet: 172.24.0.0/16
                  gateway: 172.24.0.1


