version: '2.4'

services:

    homeassistant:
        container_name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
            - ./data/homeassistant/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
            # - /var/run/restartd_signal:/var/run/restartd_signal
        restart: always
        network_mode: host
        privileged: true
        expose:
            - 8123
        environment:
            - TZ=America/Montevideo
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 279
        
     #nginx no anda con el network_mode: host entonces esto hace el reenvio
    hass-socat:
        image: rycus86/docker-socat
        container_name: hass-socat
        command: "TCP-LISTEN:8122,fork,reuseaddr TCP:172.24.0.1:8123"
        depends_on: 
            - homeassistant
        environment:       
            - VIRTUAL_HOST=homeassistant.mired
            - VIRTUAL_PORT=8122
            - CERT_NAME=nginx-selfsigned
        networks:
          my_network:
            ipv4_address: 172.24.0.5
        expose:
            - 8122
        restart: unless-stopped
        logging:
            driver: none
        # No memory limit support
        cpu_shares: 279





                
    deconz:
        container_name: deconz
        image: marthoc/deconz
        volumes:
            - ./data/deconz:/root/.local/share/dresden-elektronik/deCONZ
            - /etc/localtime:/etc/localtime:ro
        restart: always
        privileged: true
        depends_on:
            - mosquitto
        networks:
          my_network:
            ipv4_address: 172.24.0.2
        environment:
            - VIRTUAL_HOST=phoscon.mired
            - VIRTUAL_PORT=8480
            - CERT_NAME=nginx-selfsigned
            - DECONZ_WEB_PORT=8480
            - DECONZ_DEVICE=/dev/ttyACM0
            - DECONZ_WS_PORT=8443
            - DECONZ_VNC_MODE=1
        ports:
            - 8443:8443
            - 8480:8480
        devices:
            - /dev/ttyACM0
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 279
            
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - ./data/mosquitto/config:/mosquitto/config
            - ./data/mosquitto/data:/mosquitto/data
            - ./data/mosquitto/log:/mosquitto/log
        restart: always
        networks:
        #     net:
        #         ipv4_address: 172.18.0.2
            my_network:
                ipv4_address: 172.24.0.7
        ports:
        - 1883:1883
        - 9001:9001
        environment:
            - VIRTUAL_HOST=mqtt
            - VIRTUAL_PORT=1883
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        # No memory limit support
        cpu_shares: 279



networks:
    pub_net:
        external: true
    my_network:
        external: true



