version: '2.4'

services:
    reverse-proxy:
        container_name: reverse-proxy
        image: jwilder/nginx-proxy
        restart: always
        networks:
            - traefik_proxy
        ports:
            - 80:80
            - 443:443
            # - 1883:1883 # mosquito
            # - 3306:3306 # mysql
            # - 8443:8443 # phoscon deconz
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./vhost.d:/etc/nginx/vhost.d:ro"
            - ./data/nginx/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
            - ./data/nginx/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key
        logging:
            options:
                max-size: 10m
    
    portainer:
        container_name: portainer
        image: portainer/portainer:1.24.0
        restart: always
        networks:
            - traefik_proxy
        environment:
            - VIRTUAL_HOST=portainer.mired
            - VIRTUAL_PORT=9000
            - CERT_NAME=nginx-selfsigned 
        ports:
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer-data:/data
        logging:
            options:
                max-size: 10m

    # dyndns:
    #     container_name: dyndns
    #     image: oznu/cloudflare-ddns:latest
    #     restart: always
    #     networks:
    #         - host_applications
    #     environment:
    #         API_KEY: "${CLOUDFLARE_API_KEY}"
    #         ZONE: "${DYNDNS_ZONE}"
    #         SUBDOMAIN: "${DYNDNS_SUBDOMAIN}"


networks:
    # host_applications:
    #     name: applications
    #     driver: bridge
    #     ipam:
    #         config:
    #             - subnet: 172.18.0.0/24
    #               gateway: 172.18.0.1
    traefik_proxy:
        name: traefik_proxy
        driver: bridge
        ipam:
            config:
                - subnet: 172.24.0.0/16
                  gateway: 172.24.0.1


