version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    networks:
      my_network:
        ipv4_address: 172.24.0.4
    environment:
      # - VIRTUAL_HOST=pihole.mired
      # - VIRTUAL_PORT=80
      # - CERT_NAME=nginx-selfsigned
      - TZ=America/Montevideo
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.rule=Host(`pihole.mired`)"
      - "traefik.http.routers.pihole.entrypoints=internal"
      - "traefik.http.routers.pihole.tls=true"    
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - ./data/pihole/config:/etc/pihole
      - ./data/pihole/dnsmasq:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    # No memory limit support
    cpu_shares: 1024



networks:
  my_network:
    external: true

